In [1]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

print("Libraries imported successfully!")

Libraries imported successfully!

### Findings

* Successfully imported the cleaned dataset into SQLite.
* Verified 10,194 records and 21 columns.
* Confirmed that the data can be retrieved using SQL queries.

In [2]:
from pathlib import Path
import pandas as pd

# Find the project folder
current_path = Path.cwd()
project_root = current_path if (current_path / "data").exists() else current_path.parent

# Load the cleaned Superstore dataset
csv_path = project_root / "data" / "processed" / "superstore_cleaned.csv"
df = pd.read_csv(csv_path)

# Display the dataset details
print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("\nColumn names:")
print(df.columns.tolist())

# Preview the first five rows
df.head()

Dataset loaded successfully!
Number of rows: 10194
Number of columns: 21

Column names:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country_region', 'city', 'state_province', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [3]:
# Create the SQLite database connection
database_path = project_root / "data" / "database" / "superstore.db"

engine = create_engine(f"sqlite:///{database_path}")

# Import the cleaned dataset into SQLite
df.to_sql(
    name="superstore",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset imported into SQLite successfully!")

Dataset imported into SQLite successfully!

In [4]:
# Connect to the SQLite database
connection = sqlite3.connect(str(database_path))

# Verify the table and count the records
result = pd.read_sql_query(
    "SELECT COUNT(*) AS total_records FROM superstore;",
    connection
)

print("Database verification:")
display(result)

# Preview five records using SQL
preview = pd.read_sql_query(
    "SELECT * FROM superstore LIMIT 5;",
    connection
)

display(preview)

Database verification:

   total_records
0          10194

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [5]:
# Query 1: Select specific columns
query1 = """
SELECT order_id, customer_name, sales, profit
FROM superstore
LIMIT 10;
"""

# Query 2: Filter orders with sales greater than 500
query2 = """
SELECT order_id, customer_name, sales, profit
FROM superstore
WHERE sales > 500
LIMIT 10;
"""

# Query 3: Sort orders by sales, highest first
query3 = """
SELECT order_id, customer_name, sales
FROM superstore
ORDER BY sales DESC
LIMIT 10;
"""

print("Query 1: Selected columns")
display(pd.read_sql_query(query1, connection))

print("Query 2: Sales greater than 500")
display(pd.read_sql_query(query2, connection))

print("Query 3: Top 10 orders by sales")
display(pd.read_sql_query(query3, connection))

Query 1: Selected columns

         order_id  customer_name     sales    profit
0  US-2023-103800  Darren Powers    16.448    5.5512
1  US-2023-112326  Phillina Ober     3.540   -5.4870
2  US-2023-112326  Phillina Ober    11.784    4.2717
3  US-2023-112326  Phillina Ober   272.736  -64.7748
4  US-2023-141817     Mick Brown    19.536    4.8840
5  US-2023-167199  Maria Etezadi  2573.820  746.4078
6  US-2023-167199  Maria Etezadi     5.480    1.4796
7  US-2023-106054  Jack O'Briant    12.780    5.2398
8  US-2023-167199  Maria Etezadi   609.980  274.4910
9  US-2023-167199  Maria Etezadi    31.120    0.3112

Query 2: Sales greater than 500

         order_id      customer_name    sales    profit
0  US-2023-167199      Maria Etezadi  2573.82  746.4078
1  US-2023-167199      Maria Etezadi   609.98  274.4910
2  US-2023-167199      Maria Etezadi   755.96  204.1092
3  US-2023-109232  Natalie DeCherney   545.94   87.3504
4  US-2023-162775    Chris Selesnick   572.58   34.3548
5  US-2023-157147       Brian Dahlen  1325.85  238.6530
6  US-2023-162775    Chris Selesnick   646.74  258.6960
7  US-2023-147627       Hunter Lopez  1067.94  224.2674
8  US-2023-147627       Hunter Lopez   699.93  181.9818
9  US-2023-127614   Natalie Fritzler  1256.22   75.3732

Query 3: Top 10 orders by sales

         order_id       customer_name      sales
0  US-2023-145317         Sean Miller  22638.480
1  US-2025-118689        Tamara Chand  17499.950
2  US-2026-140151        Raymond Buch  13999.960
3  US-2026-127180        Tom Ashbrook  11199.968
4  US-2026-166709        Hunter Lopez  10499.970
5  US-2025-117121       Adrian Barton   9892.740
6  US-2023-116904        Sanjit Chand   9449.950
7  US-2025-107440        Bill Shonely   9099.930
8  US-2025-158841        Sanjit Engle   8749.950
9  US-2025-143714  Christopher Conant   8399.976

### Findings

* `SELECT` retrieves the required columns from the dataset.
* `WHERE` filters records based on conditions.
* `ORDER BY` sorts records by sales.
* `LIMIT` restricts the number of displayed rows.

In [6]:
# Query 4: Total sales by product category
query4 = """
SELECT
    category,
    SUM(sales) AS total_sales,
    AVG(sales) AS average_sales,
    COUNT(*) AS total_orders
FROM superstore
GROUP BY category
ORDER BY total_sales DESC;
"""

# Query 5: Categories with total sales greater than 100000
query5 = """
SELECT
    category,
    SUM(sales) AS total_sales
FROM superstore
GROUP BY category
HAVING SUM(sales) > 100000
ORDER BY total_sales DESC;
"""

# Query 6: Overall sales and profit statistics
query6 = """
SELECT
    COUNT(*) AS total_records,
    SUM(sales) AS total_sales,
    AVG(sales) AS average_sales,
    MIN(sales) AS minimum_sales,
    MAX(sales) AS maximum_sales,
    SUM(profit) AS total_profit
FROM superstore;
"""

print("Query 4: Sales by category")
display(pd.read_sql_query(query4, connection))

print("Query 5: Categories with sales above 100000")
display(pd.read_sql_query(query5, connection))

print("Query 6: Overall sales and profit statistics")
display(pd.read_sql_query(query6, connection))

Query 4: Sales by category

          category  total_sales  average_sales  total_orders
0       Technology  839893.2790     450.344922          1865
1        Furniture  754747.7613     342.911295          2201
2  Office Supplies  731893.3140     119.434288          6128

Query 5: Categories with sales above 100000

          category  total_sales
0       Technology  839893.2790
1        Furniture  754747.7613
2  Office Supplies  731893.3140

Query 6: Overall sales and profit statistics

,total_records,total_sales,average_sales,minimum_sales,maximum_sales,total_profit
0,10194,2.326534e+06,228.225854,0.444,22638.48,292296.8146

### Findings

* Technology recorded the highest total sales, followed by Furniture and Office Supplies.
* Aggregate functions summarize sales, profit, and record counts.
* `HAVING` filters grouped results based on specified conditions.

In [7]:
# Create two small tables for JOIN practice
connection.execute("DROP TABLE IF EXISTS customers_practice;")
connection.execute("DROP TABLE IF EXISTS orders_practice;")

connection.execute("""
CREATE TABLE customers_practice AS
SELECT DISTINCT customer_id, customer_name, segment
FROM superstore;
""")

connection.execute("""
CREATE TABLE orders_practice AS
SELECT order_id, customer_id, sales, profit
FROM superstore;
""")

connection.commit()

# Query 7: INNER JOIN
query7 = """
SELECT
    c.customer_name,
    c.segment,
    o.order_id,
    o.sales
FROM customers_practice AS c
INNER JOIN orders_practice AS o
    ON c.customer_id = o.customer_id
LIMIT 10;
"""

# Query 8: LEFT JOIN
query8 = """
SELECT
    c.customer_name,
    c.segment,
    o.order_id,
    o.sales
FROM customers_practice AS c
LEFT JOIN orders_practice AS o
    ON c.customer_id = o.customer_id
LIMIT 10;
"""

print("Query 7: INNER JOIN")
display(pd.read_sql_query(query7, connection))

print("Query 8: LEFT JOIN")
display(pd.read_sql_query(query8, connection))

Query 7: INNER JOIN

   customer_name   segment        order_id    sales
0  Darren Powers  Consumer  US-2023-103800   16.448
1  Darren Powers  Consumer  US-2023-122609   25.128
2  Darren Powers  Consumer  US-2023-122609  127.984
3  Darren Powers  Consumer  US-2024-105347   14.700
4  Darren Powers  Consumer  US-2024-105347  368.910
5  Darren Powers  Consumer  US-2024-115742    6.160
6  Darren Powers  Consumer  US-2024-115742   38.220
7  Darren Powers  Consumer  US-2024-115742   75.180
8  Darren Powers  Consumer  US-2024-115742   89.990
9  Darren Powers  Consumer  US-2025-141180    7.764

Query 8: LEFT JOIN

   customer_name   segment        order_id    sales
0  Darren Powers  Consumer  US-2023-103800   16.448
1  Darren Powers  Consumer  US-2023-122609   25.128
2  Darren Powers  Consumer  US-2023-122609  127.984
3  Darren Powers  Consumer  US-2024-105347   14.700
4  Darren Powers  Consumer  US-2024-105347  368.910
5  Darren Powers  Consumer  US-2024-115742    6.160
6  Darren Powers  Consumer  US-2024-115742   38.220
7  Darren Powers  Consumer  US-2024-115742   75.180
8  Darren Powers  Consumer  US-2024-115742   89.990
9  Darren Powers  Consumer  US-2025-141180    7.764

**Finding:** 
INNER JOIN returns only records with matching values in both tables.
LEFT JOIN returns all customers, including those without matching orders.

In [9]:
# Create the demo tables again
connection.execute("DROP TABLE IF EXISTS demo_customers;")
connection.execute("DROP TABLE IF EXISTS demo_orders;")

connection.execute("""
CREATE TABLE demo_customers (
    customer_id TEXT,
    customer_name TEXT
);
""")

connection.execute("""
INSERT INTO demo_customers VALUES
('C1', 'Anu'),
('C2', 'Ravi'),
('C3', 'Meena');
""")

connection.execute("""
CREATE TABLE demo_orders (
    order_id TEXT,
    customer_id TEXT,
    sales REAL
);
""")

connection.execute("""
INSERT INTO demo_orders VALUES
('O1', 'C1', 500),
('O2', 'C2', 300);
""")

connection.commit()

print("Demo tables created successfully!")

Demo tables created successfully!

In [10]:
print("INNER JOIN:")
display(pd.read_sql_query("""
SELECT c.customer_name, o.order_id, o.sales
FROM demo_customers c
INNER JOIN demo_orders o
ON c.customer_id = o.customer_id;
""", connection))

print("LEFT JOIN:")
display(pd.read_sql_query("""
SELECT c.customer_name, o.order_id, o.sales
FROM demo_customers c
LEFT JOIN demo_orders o
ON c.customer_id = o.customer_id;
""", connection))

INNER JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0

LEFT JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0
2         Meena     None    NaN

In [11]:
print("INNER JOIN:")
display(pd.read_sql_query("""
SELECT c.customer_name, o.order_id, o.sales
FROM demo_customers c
INNER JOIN demo_orders o
ON c.customer_id = o.customer_id;
""", connection))

print("LEFT JOIN:")
display(pd.read_sql_query("""
SELECT c.customer_name, o.order_id, o.sales
FROM demo_customers c
LEFT JOIN demo_orders o
ON c.customer_id = o.customer_id;
""", connection))

INNER JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0

LEFT JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0
2         Meena     None    NaN

In [12]:
print("Customers in demo_customers:")
display(pd.read_sql_query(
    "SELECT * FROM demo_customers;",
    connection
))

print("Orders in demo_orders:")
display(pd.read_sql_query(
    "SELECT * FROM demo_orders;",
    connection
))

Customers in demo_customers:

  customer_id customer_name
0          C1           Anu
1          C2          Ravi
2          C3         Meena

Orders in demo_orders:

  order_id customer_id  sales
0       O1          C1  500.0
1       O2          C2  300.0

In [13]:
print("RIGHT JOIN:")

display(pd.read_sql_query("""
SELECT
    c.customer_name,
    o.order_id,
    o.sales
FROM demo_customers c
RIGHT JOIN demo_orders o
    ON c.customer_id = o.customer_id;
""", connection))

RIGHT JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0

**Finding:** RIGHT JOIN returns all orders and includes matching customer details when available.

In [14]:
print("FULL OUTER JOIN:")

display(pd.read_sql_query("""
SELECT
    c.customer_name,
    o.order_id,
    o.sales
FROM demo_customers c
FULL OUTER JOIN demo_orders o
    ON c.customer_id = o.customer_id;
""", connection))

FULL OUTER JOIN:

  customer_name order_id  sales
0           Anu       O1  500.0
1          Ravi       O2  300.0
2         Meena     None    NaN

**Finding:** FULL OUTER JOIN returns all records from both tables, including unmatched records.

In [15]:
print("Products with sales above average:")

display(pd.read_sql_query("""
SELECT order_id, product_name, sales
FROM superstore
WHERE sales > (
    SELECT AVG(sales)
    FROM superstore
)
ORDER BY sales DESC
LIMIT 10;
""", connection))

Products with sales above average:

,order_id,product_name,sales
0,US-2023-145317,Cisco TelePresence System EX90 Videoconferenci...,22638.480
1,US-2025-118689,Canon imageCLASS 2200 Advanced Copier,17499.950
2,US-2026-140151,Canon imageCLASS 2200 Advanced Copier,13999.960
3,US-2026-127180,Canon imageCLASS 2200 Advanced Copier,11199.968
4,US-2026-166709,Canon imageCLASS 2200 Advanced Copier,10499.970
5,US-2025-117121,GBC Ibimaster 500 Manual ProClick Binding System,9892.740
6,US-2023-116904,Ibico EPK-21 Electric Binding System,9449.950
7,US-2025-107440,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930
8,US-2025-158841,HP Designjet T520 Inkjet Large Format Printer ...,8749.950
9,US-2025-143714,Canon imageCLASS 2200 Advanced Copier,8399.976

**Finding:** The subquery identifies records with sales greater than the dataset's average sales.

In [16]:
print("Category-wise sales using a CTE:")

display(pd.read_sql_query("""
WITH category_sales AS (
    SELECT
        category,
        SUM(sales) AS total_sales,
        AVG(sales) AS average_sales
    FROM superstore
    GROUP BY category
)
SELECT
    category,
    total_sales,
    average_sales
FROM category_sales
ORDER BY total_sales DESC;
""", connection))

Category-wise sales using a CTE:

          category  total_sales  average_sales
0       Technology  839893.2790     450.344922
1        Furniture  754747.7613     342.911295
2  Office Supplies  731893.3140     119.434288

**Finding:** Technology recorded the highest total sales, followed by Furniture and Office Supplies.

In [17]:
print("Ranking orders by sales within each category:")

display(pd.read_sql_query("""
SELECT
    category,
    order_id,
    product_name,
    sales,
    ROW_NUMBER() OVER (
        PARTITION BY category
        ORDER BY sales DESC
    ) AS row_num
FROM superstore
ORDER BY category, row_num
LIMIT 15;
""", connection))

Ranking orders by sales within each category:

,category,order_id,product_name,sales,row_num
0,Furniture,US-2026-118892,HON 5400 Series Task Chairs for Big and Tall,4416.174,1
1,Furniture,US-2024-117086,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900,2
2,Furniture,US-2024-116638,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,3
3,Furniture,US-2024-126977,"Riverside Palais Royal Lawyers Bookcase, Royal...",4228.704,4
4,Furniture,US-2023-128209,DMI Eclipse Executive Suite Bookcases,4007.840,5
5,Furniture,US-2023-116246,HON 5400 Series Task Chairs for Big and Tall,3785.292,6
6,Furniture,US-2023-168494,Bretford Rectangular Conference Table Tops,3610.848,7
7,Furniture,US-2025-122903,HON 5400 Series Task Chairs for Big and Tall,3504.900,8
8,Furniture,US-2025-107104,DMI Eclipse Executive Suite Bookcases,3406.664,9
9,Furniture,US-2024-164301,Bush Advantage Collection Racetrack Conference...,3393.680,10
10,Furniture,US-2024-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,11
11,Furniture,US-2026-100111,Hon 4070 Series Pagoda Armless Upholstered Sta...,2888.127,12
12,Furniture,US-2025-126452,Bretford CR8500 Series Meeting Room Furniture,2887.056,13
13,Furniture,US-2023-120474,Office Star - Professional Matrix Back Chair w...,2807.840,14
14,Furniture,US-2024-164777,HON 5400 Series Task Chairs for Big and Tall,2803.920,15

**Finding:** ROW_NUMBER() assigns a unique sequential number to each record within its category, ordered by sales.

In [18]:
print("Ranking orders by sales within each category:")

display(pd.read_sql_query("""
SELECT
    category,
    order_id,
    product_name,
    sales,
    RANK() OVER (
        PARTITION BY category
        ORDER BY sales DESC
    ) AS sales_rank
FROM superstore
ORDER BY category, sales_rank
LIMIT 15;
""", connection))

Ranking orders by sales within each category:

,category,order_id,product_name,sales,sales_rank
0,Furniture,US-2026-118892,HON 5400 Series Task Chairs for Big and Tall,4416.174,1
1,Furniture,US-2024-117086,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900,2
2,Furniture,US-2024-116638,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,3
3,Furniture,US-2024-126977,"Riverside Palais Royal Lawyers Bookcase, Royal...",4228.704,4
4,Furniture,US-2023-128209,DMI Eclipse Executive Suite Bookcases,4007.840,5
5,Furniture,US-2023-116246,HON 5400 Series Task Chairs for Big and Tall,3785.292,6
6,Furniture,US-2023-168494,Bretford Rectangular Conference Table Tops,3610.848,7
7,Furniture,US-2025-122903,HON 5400 Series Task Chairs for Big and Tall,3504.900,8
8,Furniture,US-2025-107104,DMI Eclipse Executive Suite Bookcases,3406.664,9
9,Furniture,US-2024-164301,Bush Advantage Collection Racetrack Conference...,3393.680,10
10,Furniture,US-2024-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,11
11,Furniture,US-2026-100111,Hon 4070 Series Pagoda Armless Upholstered Sta...,2888.127,12
12,Furniture,US-2025-126452,Bretford CR8500 Series Meeting Room Furniture,2887.056,13
13,Furniture,US-2023-120474,Office Star - Professional Matrix Back Chair w...,2807.840,14
14,Furniture,US-2024-164777,HON 5400 Series Task Chairs for Big and Tall,2803.920,15

**Finding:** RANK() assigns ranks based on sales within each category. Equal sales values receive the same rank.

In [19]:
print("Comparing current sales with previous sales:")

display(pd.read_sql_query("""
SELECT
    order_date,
    order_id,
    sales,
    LAG(sales) OVER (
        ORDER BY order_date
    ) AS previous_sales
FROM superstore
ORDER BY order_date
LIMIT 10;
""", connection))

Comparing current sales with previous sales:

   order_date        order_id     sales  previous_sales
0  2023-01-03  US-2023-103800    16.448             NaN
1  2023-01-04  US-2023-112326     3.540          16.448
2  2023-01-04  US-2023-112326    11.784           3.540
3  2023-01-04  US-2023-112326   272.736          11.784
4  2023-01-05  US-2023-141817    19.536         272.736
5  2023-01-06  US-2023-167199  2573.820          19.536
6  2023-01-06  US-2023-167199     5.480        2573.820
7  2023-01-06  US-2023-106054    12.780           5.480
8  2023-01-06  US-2023-167199   609.980          12.780
9  2023-01-06  US-2023-167199    31.120         609.980

**Finding:** LAG() retrieves the previous row's sales value for comparison with the current row.

In [20]:
print("Comparing current sales with next sales:")

display(pd.read_sql_query("""
SELECT
    order_date,
    order_id,
    sales,
    LEAD(sales) OVER (
        ORDER BY order_date
    ) AS next_sales
FROM superstore
ORDER BY order_date
LIMIT 10;
""", connection))

Comparing current sales with next sales:

   order_date        order_id     sales  next_sales
0  2023-01-03  US-2023-103800    16.448       3.540
1  2023-01-04  US-2023-112326     3.540      11.784
2  2023-01-04  US-2023-112326    11.784     272.736
3  2023-01-04  US-2023-112326   272.736      19.536
4  2023-01-05  US-2023-141817    19.536    2573.820
5  2023-01-06  US-2023-167199  2573.820       5.480
6  2023-01-06  US-2023-167199     5.480      12.780
7  2023-01-06  US-2023-106054    12.780     609.980
8  2023-01-06  US-2023-167199   609.980      31.120
9  2023-01-06  US-2023-167199    31.120       6.540

**Finding:** LEAD() retrieves the next row's sales value for comparison with the current row.

In [21]:
print("Monthly sales trends:")

display(pd.read_sql_query("""
SELECT
    strftime('%Y-%m', order_date) AS sales_month,
    SUM(sales) AS total_sales
FROM superstore
GROUP BY strftime('%Y-%m', order_date)
ORDER BY sales_month;
""", connection))

Monthly sales trends:

   sales_month  total_sales
0      2023-01   14518.0550
1      2023-02    4519.8920
2      2023-03   56933.9090
3      2023-04   28295.3450
4      2023-05   26319.7670
5      2023-06   34669.4796
6      2023-07   33946.3930
7      2023-08   28918.3385
8      2023-09   82670.4288
9      2023-10   32413.3390
10     2023-11   78826.9567
11     2023-12   72008.3085
12     2024-01   18461.9156
13     2024-02   11951.4110
14     2024-03   39978.6280
15     2024-04   34195.2085
16     2024-05   30246.9465
17     2024-06   24797.2920
18     2024-07   28765.3250
19     2024-08   37057.0042
20     2024-09   64627.0460
21     2024-10   31407.1335
22     2024-11   75972.5635
23     2024-12   75532.5572
24     2025-01   18830.3310
25     2025-02   22978.8150
26     2025-03   53031.0690
27     2025-04   38829.1590
28     2025-05   57042.8380
29     2025-06   40937.1480
30     2025-07   40300.4990
31     2025-08   31716.8143
32     2025-09   73521.6629
33     2025-10   59831.0010
34     2025-11   79411.9658
35     2025-12   97502.2770
36     2026-01   44259.2140
37     2026-02   20301.1334
38     2026-03   60728.4808
39     2026-04   36779.0361
40     2026-05   45155.4822
41     2026-06   53056.0777
42     2026-07   45989.4960
43     2026-08   64129.7580
44     2026-09   88064.5320
45     2026-10   83474.7832
46     2026-11  118454.5050
47     2026-12   85175.0328

### Findings

* Monthly sales totals help identify changes in sales over time.
* Comparing months helps identify high-performing and low-performing periods.

In [22]:
print("Top 10 customers by total sales:")

display(pd.read_sql_query("""
SELECT
    customer_id,
    customer_name,
    SUM(sales) AS total_revenue
FROM superstore
GROUP BY customer_id, customer_name
ORDER BY total_revenue DESC
LIMIT 10;
""", connection))

Top 10 customers by total sales:

  customer_id       customer_name  total_revenue
0    SM-20320         Sean Miller      25043.050
1    TC-20980        Tamara Chand      19052.218
2    RB-19360        Raymond Buch      15117.339
3    TA-21385        Tom Ashbrook      14595.620
4    AB-10105       Adrian Barton      14473.571
5    KL-16645        Ken Lonsdale      14175.229
6    SC-20095        Sanjit Chand      14142.334
7    HL-15040        Hunter Lopez      12873.298
8    SE-20110        Sanjit Engle      12209.438
9    CC-12370  Christopher Conant      12129.072

### Findings

* The query identifies the top 10 customers based on total sales.
* These customers contribute the highest sales among the customers listed.

In [23]:
print("Customer retention analysis:")

display(pd.read_sql_query("""
WITH customer_months AS (
    SELECT DISTINCT
        customer_id,
        strftime('%Y-%m', order_date) AS order_month
    FROM superstore
),
customer_activity AS (
    SELECT
        customer_id,
        COUNT(*) AS active_months
    FROM customer_months
    GROUP BY customer_id
)
SELECT
    COUNT(*) AS total_customers,
    SUM(
        CASE WHEN active_months > 1 THEN 1 ELSE 0 END
    ) AS repeat_month_customers,
    ROUND(
        100.0 * SUM(
            CASE WHEN active_months > 1 THEN 1 ELSE 0 END
        ) / COUNT(*), 2
    ) AS repeat_month_customer_percentage
FROM customer_activity;
""", connection))

Customer retention analysis:

   total_customers  repeat_month_customers  repeat_month_customer_percentage
0              804                     790                             98.26

### Findings

* The query identifies customers who placed orders in more than one month.
* The repeat-month customer percentage indicates how frequently customers return across different months.

In [25]:
print("Product category performance:")

display(pd.read_sql_query("""
SELECT
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    COUNT(*) AS total_records
FROM superstore
GROUP BY category
ORDER BY total_sales DESC;
""", connection))

Product category performance:

          category  total_sales  total_profit  total_records
0       Technology  839893.2790   146543.3756           1865
1        Furniture  754747.7613    19729.9956           2201
2  Office Supplies  731893.3140   126023.4434           6128

### Findings

* The query compares total sales and profit across product categories.
* It also counts the records in each category.
* The results help identify categories with stronger sales and profitability.

In [26]:
print("Monthly sales with a 3-month moving average:")

display(pd.read_sql_query("""
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', order_date) AS sales_month,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY strftime('%Y-%m', order_date)
)
SELECT
    sales_month,
    total_sales,
    ROUND(
        AVG(total_sales) OVER (
            ORDER BY sales_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ), 2
    ) AS moving_average
FROM monthly_sales
ORDER BY sales_month;
""", connection))

Monthly sales with a 3-month moving average:

   sales_month  total_sales  moving_average
0      2023-01   14518.0550        14518.06
1      2023-02    4519.8920         9518.97
2      2023-03   56933.9090        25323.95
3      2023-04   28295.3450        29916.38
4      2023-05   26319.7670        37183.01
5      2023-06   34669.4796        29761.53
6      2023-07   33946.3930        31645.21
7      2023-08   28918.3385        32511.40
8      2023-09   82670.4288        48511.72
9      2023-10   32413.3390        48000.70
10     2023-11   78826.9567        64636.91
11     2023-12   72008.3085        61082.87
12     2024-01   18461.9156        56432.39
13     2024-02   11951.4110        34140.55
14     2024-03   39978.6280        23463.98
15     2024-04   34195.2085        28708.42
16     2024-05   30246.9465        34806.93
17     2024-06   24797.2920        29746.48
18     2024-07   28765.3250        27936.52
19     2024-08   37057.0042        30206.54
20     2024-09   64627.0460        43483.13
21     2024-10   31407.1335        44363.73
22     2024-11   75972.5635        57335.58
23     2024-12   75532.5572        60970.75
24     2025-01   18830.3310        56778.48
25     2025-02   22978.8150        39113.90
26     2025-03   53031.0690        31613.41
27     2025-04   38829.1590        38279.68
28     2025-05   57042.8380        49634.36
29     2025-06   40937.1480        45603.05
30     2025-07   40300.4990        46093.49
31     2025-08   31716.8143        37651.49
32     2025-09   73521.6629        48512.99
33     2025-10   59831.0010        55023.16
34     2025-11   79411.9658        70921.54
35     2025-12   97502.2770        78915.08
36     2026-01   44259.2140        73724.49
37     2026-02   20301.1334        54020.87
38     2026-03   60728.4808        41762.94
39     2026-04   36779.0361        39269.55
40     2026-05   45155.4822        47554.33
41     2026-06   53056.0777        44996.87
42     2026-07   45989.4960        48067.02
43     2026-08   64129.7580        54391.78
44     2026-09   88064.5320        66061.26
45     2026-10   83474.7832        78556.36
46     2026-11  118454.5050        96664.61
47     2026-12   85175.0328        95701.44

### Findings

* The query calculates monthly sales and a 3-month moving average.
* The moving average smooths monthly fluctuations and helps identify sales trends.

In [27]:
print("Cumulative monthly sales:")

display(pd.read_sql_query("""
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', order_date) AS sales_month,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY strftime('%Y-%m', order_date)
)
SELECT
    sales_month,
    total_sales,
    SUM(total_sales) OVER (
        ORDER BY sales_month
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_sales
FROM monthly_sales
ORDER BY sales_month;
""", connection))

Cumulative monthly sales:

   sales_month  total_sales  cumulative_sales
0      2023-01   14518.0550      1.451806e+04
1      2023-02    4519.8920      1.903795e+04
2      2023-03   56933.9090      7.597186e+04
3      2023-04   28295.3450      1.042672e+05
4      2023-05   26319.7670      1.305870e+05
5      2023-06   34669.4796      1.652564e+05
6      2023-07   33946.3930      1.992028e+05
7      2023-08   28918.3385      2.281212e+05
8      2023-09   82670.4288      3.107916e+05
9      2023-10   32413.3390      3.432049e+05
10     2023-11   78826.9567      4.220319e+05
11     2023-12   72008.3085      4.940402e+05
12     2024-01   18461.9156      5.125021e+05
13     2024-02   11951.4110      5.244535e+05
14     2024-03   39978.6280      5.644322e+05
15     2024-04   34195.2085      5.986274e+05
16     2024-05   30246.9465      6.288743e+05
17     2024-06   24797.2920      6.536716e+05
18     2024-07   28765.3250      6.824369e+05
19     2024-08   37057.0042      7.194939e+05
20     2024-09   64627.0460      7.841210e+05
21     2024-10   31407.1335      8.155281e+05
22     2024-11   75972.5635      8.915007e+05
23     2024-12   75532.5572      9.670332e+05
24     2025-01   18830.3310      9.858636e+05
25     2025-02   22978.8150      1.008842e+06
26     2025-03   53031.0690      1.061873e+06
27     2025-04   38829.1590      1.100703e+06
28     2025-05   57042.8380      1.157745e+06
29     2025-06   40937.1480      1.198683e+06
30     2025-07   40300.4990      1.238983e+06
31     2025-08   31716.8143      1.270700e+06
32     2025-09   73521.6629      1.344222e+06
33     2025-10   59831.0010      1.404053e+06
34     2025-11   79411.9658      1.483465e+06
35     2025-12   97502.2770      1.580967e+06
36     2026-01   44259.2140      1.625226e+06
37     2026-02   20301.1334      1.645527e+06
38     2026-03   60728.4808      1.706256e+06
39     2026-04   36779.0361      1.743035e+06
40     2026-05   45155.4822      1.788190e+06
41     2026-06   53056.0777      1.841246e+06
42     2026-07   45989.4960      1.887236e+06
43     2026-08   64129.7580      1.951366e+06
44     2026-09   88064.5320      2.039430e+06
45     2026-10   83474.7832      2.122905e+06
46     2026-11  118454.5050      2.241359e+06
47     2026-12   85175.0328      2.326534e+06

### Findings

* The query calculates monthly sales and cumulative sales over time.
* Cumulative sales show how the total sales amount increases across successive months.

In [28]:
print("Creating category sales view:")

connection.execute("""
CREATE VIEW IF NOT EXISTS category_sales_view AS
SELECT
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM superstore
GROUP BY category;
""")

connection.commit()

display(pd.read_sql_query("""
SELECT *
FROM category_sales_view
ORDER BY total_sales DESC;
""", connection))

Creating category sales view:

          category  total_sales  total_profit
0       Technology  839893.2790   146543.3756
1        Furniture  754747.7613    19729.9956
2  Office Supplies  731893.3140   126023.4434

### Findings

* Created a reusable SQL view for category-wise sales and profit.
* The view simplifies repeated queries for category performance.

In [29]:
print("Query execution plan:")

display(pd.read_sql_query("""
EXPLAIN QUERY PLAN
SELECT
    category,
    SUM(sales) AS total_sales
FROM superstore
GROUP BY category;
""", connection))

Query execution plan:

   id  parent  notused                        detail
0   6       0        0               SCAN superstore
1   8       0        0  USE TEMP B-TREE FOR GROUP BY

**Finding:** EXPLAIN QUERY PLAN displays how SQLite executes a query and helps identify opportunities to optimize query performance.

In [30]:
print("Creating an index on order_date:")

connection.execute("""
CREATE INDEX IF NOT EXISTS idx_superstore_order_date
ON superstore(order_date);
""")

connection.commit()

print("Index created successfully!")

Creating an index on order_date:
Index created successfully!

**Finding:** Created an index on `order_date` to improve query efficiency when filtering records by date.

In [31]:
display(pd.read_sql_query("""
EXPLAIN QUERY PLAN
SELECT order_id, order_date, sales
FROM superstore
WHERE order_date = '2025-01-01';
""", connection))

   id  parent  notused                                             detail
0   3       0        0  SEARCH superstore USING INDEX idx_superstore_o...

**Finding:** The query execution plan shows that SQLite uses the index on `order_date` to search for records matching the specified date.

In [32]:
from sqlalchemy import create_engine
from pathlib import Path

database_path = project_root / "data" / "database" / "superstore.db"
engine = create_engine(f"sqlite:///{database_path}")

with engine.connect() as conn:
    print("Python connected to SQLite successfully!")

Python connected to SQLite successfully!

**Finding:** Successfully established a connection between Python and the SQLite database using SQLAlchemy.

In [33]:
query = """
SELECT
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM superstore
GROUP BY category
ORDER BY total_sales DESC;
"""

result_df = pd.read_sql_query(query, engine)
display(result_df)

          category  total_sales  total_profit
0       Technology  839893.2790   146543.3756
1        Furniture  754747.7613    19729.9956
2  Office Supplies  731893.3140   126023.4434

**Finding:** SQL queries were executed through SQLAlchemy, and the results were successfully loaded into a pandas DataFrame. Technology had the highest total sales among the three product categories.

In [34]:
query = """
SELECT
    order_id,
    category,
    sales,
    profit
FROM superstore
WHERE category = ?
ORDER BY sales DESC
LIMIT 10;
"""

result_df = pd.read_sql_query(
    query,
    connection,
    params=("Technology",)
)

display(result_df)

         order_id    category      sales     profit
0  US-2023-145317  Technology  22638.480 -1811.0784
1  US-2025-118689  Technology  17499.950  8399.9760
2  US-2026-140151  Technology  13999.960  6719.9808
3  US-2026-127180  Technology  11199.968  3919.9888
4  US-2026-166709  Technology  10499.970  5039.9856
5  US-2025-107440  Technology   9099.930  2365.9818
6  US-2025-158841  Technology   8749.950  2799.9840
7  US-2025-143714  Technology   8399.976  1119.9968
8  US-2023-139892  Technology   8159.952 -1359.9920
9  US-2026-168116  Technology   7999.980 -3839.9904

In [35]:
query = """
SELECT
    order_id,
    category,
    sales,
    profit
FROM superstore
WHERE category = ?
ORDER BY sales DESC
LIMIT 10;
"""

result_df = pd.read_sql_query(
    query,
    connection,
    params=("Technology",)
)

display(result_df)

         order_id    category      sales     profit
0  US-2023-145317  Technology  22638.480 -1811.0784
1  US-2025-118689  Technology  17499.950  8399.9760
2  US-2026-140151  Technology  13999.960  6719.9808
3  US-2026-127180  Technology  11199.968  3919.9888
4  US-2026-166709  Technology  10499.970  5039.9856
5  US-2025-107440  Technology   9099.930  2365.9818
6  US-2025-158841  Technology   8749.950  2799.9840
7  US-2025-143714  Technology   8399.976  1119.9968
8  US-2023-139892  Technology   8159.952 -1359.9920
9  US-2026-168116  Technology   7999.980 -3839.9904

**Finding:** The parameterized SQL query successfully retrieves the top 10 highest-sales records for the Technology category. Using placeholders helps prevent SQL injection by separating query structure from input values.

In [2]:
import sys
from pathlib import Path

# Find the project root
current_path = Path.cwd()
project_root = (
    current_path
    if (current_path / "scripts").exists()
    else current_path.parent
)

sys.path.insert(0, str(project_root / "scripts"))

from db_utils import get_connection, get_engine, run_query

# Test 1: SQLite connection
with get_connection() as conn:
    print("SQLite connection successful!")

# Test 2: SQLAlchemy engine
engine_test = get_engine()
print("SQLAlchemy engine created successfully!")

# Test 3: Run SQL and return a DataFrame
test_df = run_query("""
    SELECT category, SUM(sales) AS total_sales
    FROM superstore
    GROUP BY category
    ORDER BY total_sales DESC;
""")

display(test_df)

SQLite connection successful!
SQLAlchemy engine created successfully!

          category  total_sales
0       Technology  839893.2790
1        Furniture  754747.7613
2  Office Supplies  731893.3140

**Finding:** Successfully tested the reusable `db_utils.py` module. The SQLite connection and SQLAlchemy engine were created successfully, and SQL query results were returned as a pandas DataFrame.